[WIP] tutorial
canonical/ubuntu-pro-for-wsl pull request #550
Opened 2024-02-08 04:42 UTC by CarlosNihelton

Not ready yet, just to have a link to share the work in progress...

2024-02-23 08:39 UTC, EduardGomezEscandell requested changes
Gave it a quick scan assuming that this comes pre-approved by Teodora as well :P

I see that you put the tutorial directly in `index.md` rather than its separate subpage. I have no strong--or really any--feelings about this, but was this on purpose? If so I suppose we should do the same with the how-to guide.

2024-02-23 08:39 UTC, EduardGomezEscandell commented on docs/tutorial/index.md
> +## Check that the new Ubuntu-Preview instance with registered in Landscape
```suggestion
## Check that the new Ubuntu-Preview instance was registered in Landscape
```

2024-02-23 08:39 UTC, EduardGomezEscandell commented on docs/tutorial/index.md
> +[Diagram]
Add a <!-- TODO: bla bla bla --> so that we can grep for this sorts of things latter.

2024-02-23 08:40 UTC, EduardGomezEscandell commented on docs/tutorial/index.md
> +[Diagram]
Funny, if don't use `tildes` GitHub hides the comment 😅 

<!-- I'm hidden 😈 -->

2024-02-23 14:12 UTC, CarlosNihelton commented
Just rebased to fix a merge conflict. No changes in the contents.

2024-02-23 14:48 UTC, tmihoc commented
> Skipping empty layers is a great idea. 

But it might not be an empty layer here after all. (Just spoke to Didier and I am now convinced we need two basic guides, 

- Set up UP4W for a single Windows host
- - Using the GUI
- - Using cloud-init  

- Set up UP4W for multiple Windows hosts at once
-- Using the registry
-- Using cloud-init

2024-02-26 13:29 UTC, EduardGomezEscandell approved these changes

2024-02-26 13:34 UTC, merged