feat(windows-agent): Log obfuscated pro token on proservice start
canonical/ubuntu-pro-for-wsl pull request #647
Opened 2024-03-04 20:42 UTC by ashuntu

Added log statements for when the proservice is created, logging the obfuscated token being used or "No token loaded" if no existing token is found.

---

UDENG-2354

2024-03-05 07:05 UTC, didrocks requested changes
Thanks for looking into this and adding a test for it! My few notes is on the technical side itself with where things could be improved.

Your changes matches the card description itself which may not have been accurate. IIRC, we have one place where the Windows agent is logging the token in plain text and that was what supposed to be replaced. I don’t think that loading it on `New` is required with the event mechanism that Edu put in place, but I will let @EduardGomezEscandell  comment on that. However, conceptually, we are loading the token from the registry, this is the place where there is a change that it should be logged (apart from the error handling of course) and obfuscated.



See my remark inline about the

2024-03-05 07:05 UTC, didrocks commented on windows-agent/internal/proservices/proservices_test.go
> +				err := reg.WriteValue(k, "UbuntuProToken", defaultProToken, false)
ok, you are writing the token here but the only assertion you are doing is that there is no error.

You don’t assert that:
- there is a token loaded when we got one in the registry
- the token itself is obfuscated (checking for `*` in the retrieved token.

2024-03-05 17:23 UTC, CarlosNihelton approved these changes
Looking at both agent's and wsl-pro-service logs I didn't spot any other place where we'd log the pro token verbatim.

So, LGTM!

2024-03-06 06:49 UTC, didrocks approved these changes
Excellent!

Do you mind renaming the PR title itself (and the description), as it’s not accurate anymore and will be used in the merge commit? Then, feel free to merge :)

@EduardGomezEscandell: FYI, we took the liberty to rename `getSubscriptionInfo` to `getSubscriptionSource`, because this methods returns an info object, but only with the source field set. I was undecided in between this and returning only the source and wrapping it again afterward, but let’s start with that. At least, this is a little bit more clear now that we don’t return the token from it!

2024-03-06 18:08 UTC, merged