feat(wsl-pro-service): Add default wsl tag to Landscape configs
canonical/ubuntu-pro-for-wsl pull request #683
Opened 2024-03-11 21:03 UTC by ashuntu

This PR extends the already-existing modifications we make to Landscape configs in `wsl-pro-service`. It appends `tags = wsl` to the Landscape config if a `tags` key doesn't already exist. Any `tags` already present in the config (including empty tags) are *not* overridden.

*For review, the [Landscape example configuration](https://github.com/canonical/landscape-client/blob/master/example.conf#L167) may be useful.*

---

UDENG-2372

2024-03-11 21:06 UTC, ashuntu commented on wsl-pro-service/internal/system/testdata/TestLandscapeEnable/golden/success_when_empty_tags_are_present
This weird diff is a side effect of me deleting an unused golden file

2024-03-11 21:55 UTC, ashuntu commented
Codecov is complaining about lines that were also previously not covered. Everything added is covered to the same degree as was previously.

2024-03-12 15:49 UTC, EduardGomezEscandell approved these changes
Great!

2024-03-12 15:54 UTC, CarlosNihelton approved these changes
It's hard to break that `createKey` function because most of the things we could do in test environment to break it would break before reaching it.

2024-03-14 07:16 UTC, didrocks requested changes
I do have one small request in test name, but otherwise, excellent, thanks for looking at the fixtures and golden files!

2024-03-14 07:16 UTC, didrocks commented on wsl-pro-service/internal/system/system_test.go
> +		"Success when custom tags are present":       {},
nitpick: I would change the name here to be more explicit than just "Success", like "Do not append wsl when config tag is provided but empty" and "Do not append wsl tag when config tag is provided"

2024-03-18 20:27 UTC, merged