refactor(wslserviceapi): Remove double server in WSL
canonical/ubuntu-pro-for-wsl pull request #697
Opened 2024-03-19 10:54 UTC by EduardGomezEscandell

New diagram 🖌️ 

![image](https://github.com/canonical/ubuntu-pro-for-wsl/assets/47142856/45825bfc-fa75-43cc-b1bc-d789e56a8d7d)

---

UDENG-2509

2024-03-25 14:30 UTC, didrocks requested changes
Really happy to see this!

So, there are many comments, but nothing on the logic itself. Mostly formatting and for better maintainability in the long term.
Thanks again for tackling this non trivial tasks!

Btw, you need to update your diagram :)

2024-03-25 14:52 UTC, EduardGomezEscandell commented on windows-agent/internal/proservices/wslinstance/proattachement.go
> +// SetProStream sets the pro attachment stream for the client.
Where is golangci-lint when you need it 😭

2024-03-25 14:56 UTC, EduardGomezEscandell commented on windows-agent/internal/tasks/pro_attachment.go
> +	err := conn.SendProAttachment(t.Token)
Yess

2024-03-25 15:01 UTC, EduardGomezEscandell commented on wsl-pro-service/internal/streams/multiclient.go
> +//nolint:revive // This method is only public to tests, where multiClient has an alias available
That leads to another false positive in the export_test file 😄 

```go
// export_test.go

type MultiClient = multiClient

func Connect(ctx context.Context, conn *grpc.ClientConn) (c *MultiClient, err error) {
//                                                           ^^^^^^^^^^^
// unexported-return: exported func Connect returns unexported type *streams.multiClient, which can be annoying to use (revive)
	return connect(ctx, conn)
}
```

2024-03-25 15:05 UTC, EduardGomezEscandell commented on wsl-pro-service/internal/streams/server.go
> +// Package streams abstracts the bi-directional gRPC stream and provides a faux server that mimics a unary call server.
Fake: ❌ cheap copy, untrustworthy
Faux: 🥖 Refined, elegant disguise

2024-03-25 15:09 UTC, EduardGomezEscandell commented on wsl-pro-service/internal/streams/server.go
> +		log.Debugf(ctx, "Started serving %s requests", reflect.TypeOf((*Command)(nil)).Elem())
Clearly!

2024-03-25 16:16 UTC, EduardGomezEscandell commented on windows-agent/internal/proservices/wslinstance/client.go
> +		return errors.New("stream already connected")
Fun fact: there was a bug here! Kinda, depends on what the desired behaviour is. Connecting with a secnd stream would drop both the first and second ones.

2024-03-25 16:19 UTC, EduardGomezEscandell commented on windows-agent/internal/proservices/wslinstance/wslinstance.go
> +		return err
A single test can cover all three cases :)

2024-03-25 17:00 UTC, didrocks commented on windows-agent/internal/proservices/wslinstance/client.go
> +		return errors.New("stream already connected")
\o/

2024-03-25 17:07 UTC, didrocks commented on wsl-pro-service/internal/streams/server.go
> +// Package streams abstracts the bi-directional gRPC stream and provides a faux server that mimics a unary call server.
De toute évidence !

2024-03-25 17:08 UTC, CarlosNihelton commented on windows-agent/internal/proservices/wslinstance/proattachment.go
🤣

2024-03-25 17:10 UTC, didrocks requested changes
Ok, there is only one comment about the exported function (despite the other false positive linting warning) that I think is worth changing! Thanks for fixing them all so quickly :)

2024-03-26 02:32 UTC, CarlosNihelton reviewed
Two nitpicks for you.

I must rely on both of you guys on the implementation details. This is far too big to fit in my head, despite its considerable size :)

2024-03-26 02:32 UTC, CarlosNihelton commented on windows-agent/internal/proservices/wslinstance/client.go
> +// will be false.
```suggestion
// msgToError translates a result received via gRPC into an error.
// If there is a problem translating, an error will be returned and the first return value
// will be false.
```

2024-03-26 02:32 UTC, CarlosNihelton commented on windows-agent/internal/proservices/wslinstance/landscapeconfig.go
> +// SetLandscapeConfigStream sets the landscape config stream for the client.
```suggestion
// SetLandscapeConfigStream sets the Landscape config stream for the client.
```

I think we should capitalize all instances of the word `Landscape`.

2024-03-26 09:25 UTC, EduardGomezEscandell commented
Yeah we did a pair review with liveshare and all, too big a PR to review the usual way :)

2024-03-26 13:14 UTC, didrocks approved these changes
Thanks for the overall logical simplifcation!

2024-03-26 17:42 UTC, merged