feat(windows-agent): Add support for configuration files
canonical/ubuntu-pro-for-wsl pull request #721
Opened 2024-04-10 22:35 UTC by ashuntu

This adds support for a configuration file to be read and used. Currently, the only options available are verbosity level.

Config files can be located in the current working directory, alongside the binary, in the user's home directory, or in `%UserProfile%/.ubuntupro`. The file must be named `ubuntu-pro-agent.<type>` where `<type>` is one of the file types [supported by Viper](https://github.com/spf13/viper?tab=readme-ov-file#reading-config-files), e.g. `ubuntu-pro-agent.yaml`.

A custom configuration path can be specified by passing the new `--config` flag, which should point to a file that meets the same requirements of Viper described above.

---

UDENG-2369

2024-04-17 20:06 UTC, CarlosNihelton approved these changes
Good job! But I think there are a few details to be sorted out. Nothing major though.

2024-04-17 20:06 UTC, CarlosNihelton commented on windows-agent/cmd/ubuntu-pro-agent/agent/config.go
> +	}
You could add one small test function in agent_test.go, similar to `TestNoUsageError` for example, that writes a config file setting the verbosity level to the maximum in one of the supported locations before starting the agent and looking for that file path in the captured stdout.

2024-04-17 20:07 UTC, CarlosNihelton requested changes
Sorry, I approved by mistake.

2024-04-23 14:24 UTC, CarlosNihelton requested changes
Almost there, just one minor detail.

2024-04-23 14:24 UTC, CarlosNihelton commented on windows-agent/cmd/ubuntu-pro-agent/agent/agent.go
> +
If that's just for testing you should move that method to a file in the same package named `export_test.go`. This way the method is only visible in tests.

2024-04-23 19:44 UTC, ashuntu commented
Still a test failing in another area of the code, any idea why?

2024-04-24 02:03 UTC, CarlosNihelton commented
> Still a test failing in another area of the code, any idea why?

I think that's the flaky behavior Didier mentioned and we need to investigate.

2024-04-24 02:03 UTC, CarlosNihelton approved these changes
LGMT :tada:

2024-04-24 15:15 UTC, merged