feat(windows-agent): Send CommandStatus messages to Landscape server
canonical/ubuntu-pro-for-wsl pull request #948
Opened 2024-11-12 18:17 UTC by CarlosNihelton

Matched by the server issued request ID.

With https://github.com/canonical/landscape-hostagent-api/pull/20 and https://github.com/canonical/landscape-hostagent-api/pull/21, the Landscape hostagent API now allows the server to assign a request ID when sending a command and receive feedback from the Windows agent on the status of handling such command, which is also a good vehicle for reporting errors back to the server.

This PR changes the Landscape command executor component inside the Windows agent to enforce sending status messages as the command handling proceeds. As each command handler method knows best when all validation steps are finished and the actual execution started, I'm deliberately passing the request ID. Except for the AssignHost command. That's special because the server sends it as a one-shot command and terminates the connection. There is no feedback expected. The actual feedback is a new connection with the hostagent_UID assigned.

A new test function is introduced to validate that commands send status messages, for which I had to change the Landscape mock server to keep a log of such messages for later evaluation. Testing the commands themselves is not the objective here, but rather assert that status messages are sent.

---

UDENG-1174

2024-11-13 15:24 UTC, didrocks requested changes
Excellent! This is way less changes that I initially anticipated for that feature. This is really well executed :)

I have few suggestions ofc, tell me what you think about them!

2024-11-13 17:39 UTC, CarlosNihelton commented on common/wsltestutils/wsl_windows.go
> +	out, err := exec.Command("powershell", "-NoProfile", "-Command", cmd).CombinedOutput()
Making powershell output as nice as it can be :)

2024-11-13 18:07 UTC, CarlosNihelton commented on windows-agent/internal/proservices/landscape/executor.go
> +func (e executor) setDefault(ctx context.Context, cmd *landscapeapi.Command_SetDefault, requestID string) error {
Indeed most of the times we're just passing it along the call chain. It's a pefect fit for `context.WithValue()` /`context.Value()` pair.

2024-11-18 15:56 UTC, didrocks approved these changes
Perfect! Thanks a lot for the changes! :)

Very good work on that PR! Well done!

2024-11-18 16:56 UTC, merged